# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_roomname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomName',
            field=models.CharField(max_length=64),
        ),
    ]
