# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=12)),
                ('mdp', models.CharField(max_length=12)),
                ('mail', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='reponse',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Utilisateur'),
        ),
        migrations.AddField(
            model_name='question',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Utilisateur'),
        ),
        migrations.AddField(
            model_name='amis',
            name='amisde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amis_ami', to='core.Utilisateur'),
        ),
        migrations.AddField(
            model_name='amis',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amis_base', to='core.Utilisateur'),
        ),
    ]
