# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amis',
            name='amisde',
        ),
        migrations.RemoveField(
            model_name='amis',
            name='utilisateur',
        ),
        migrations.AlterField(
            model_name='question',
            name='utilisateur',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='utilisateur',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Amis',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
