# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170308_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=20)),
                ('mdp', models.CharField(max_length=32)),
                ('mail', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='amis',
            name='amisde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amis_ami', to='core.Utilisateur'),
        ),
        migrations.AddField(
            model_name='amis',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amis_base', to='core.Utilisateur'),
        ),
    ]
