# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170308_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='question',
        ),
    ]
